### ISSUE TITLE
adservice was killed

### ISSUE THREAD

**Issue by Frapschen** [openinsight-proj/adservice#18]
adservice log:
```
2022-11-28 08:17:45.202 trace_id= span_id= trace_flags=  INFO 7 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [271eaade-96b0-45bf-bfc6-a6460184daa2_config-0] fail to connect server,after trying 31 times, last try server is {serverIp='nacos-test.skoala-test', server main port=8848},error=unknown
2022-11-28 08:17:46.326 trace_id= span_id= trace_flags= ERROR 7 --- [s.client.Worker] com.alibaba.nacos.common.remote.client   : Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=99b9152e6137471786d4aff22fb3c08f, Client-RequestTS=1669623466224, exConfigInfo=true, Timestamp=1669623466224}, requestId='null'}, retryTimes=0,errorMessage=Client not connected,current status:STARTING
2022-11-28 08:17:46.427 trace_id= span_id= trace_flags= ERROR 7 --- [s.client.Worker] com.alibaba.nacos.common.remote.client   : Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=99b9152e6137471786d4aff22fb3c08f, Client-RequestTS=1669623466224, exConfigInfo=true, Timestamp=1669623466224}, requestId='null'}, retryTimes=1,errorMessage=Client not connected,current status:STARTING
2022-11-28 08:17:46.527 trace_id= span_id= trace_flags= ERROR 7 --- [s.client.Worker] com.alibaba.nacos.common.remote.client   : Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=99b9152e6137471786d4aff22fb3c08f, Client-RequestTS=1669623466224, exConfigInfo=true, Timestamp=1669623466224}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:STARTING
2022-11-28 08:17:46.529 trace_id= span_id= trace_flags= ERROR 7 --- [s.client.Worker] c.a.n.client.config.impl.ClientWorker    : Async listen config change error 

com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655) ~[nacos-client-2.0.3.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1067) ~[nacos-client-2.0.3.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1042) ~[nacos-client-2.0.3.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:831) ~[nacos-client-2.0.3.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$4.run(ClientWorker.java:748) ~[nacos-client-2.0.3.jar!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

Killed
```

**Comment by Frapschen** [comment]
we need add `-Dspring.cloud.nacos.config.enabled=false` to opentelemetry-demo chart repo

**Comment by Frapschen** [comment]
> we need add `-Dspring.cloud.nacos.config.enabled=false` to opentelemetry-demo chart repo

fix by https://github.com/openinsight-proj/openinsight-helm-charts/pull/57

**Comment by Frapschen** [comment]
fix by https://github.com/openinsight-proj/adservice/pull/27
